#!/bin/bash

# need to install gpiod on raspberry pi

# sudo apt update
# sudo apt install gpiod
INPUT_PIN=17
OUTPUT_PIN=18

while true; do
    state17 = $(gpioget gpiochip0 $INPUT_PIN)
    gpioset gpiochip0 $OUTPUT_PIN = $state17
done
